/*==========================================================================*/

#include <a_samp>
#include <Dini>
#include <gameinfo>
#include <utils>
#include <morphinc>
#include <veh>
//===========================================================================
#define C_WHITE "{FFFFFF}"
#define C_RED "{CC0033}"
#define C_LBLUE "{00C0FF}"
#define C_GREY "{C3C3C3}"
#define C_YELLOW "{FFFF33}"


// ¡¶¿€¿⁄ [OMC]M.Bruce
